### ISSUE TITLE
Issue with new n8n instances

### ISSUE THREAD

**Issue by jakevis** [n8n-community-node/n8n-nodes-mastodon#8]
Seems something broke in a recent n8n update... every upload I am seeing this now:

2023-03-17T22:58:33.807Z | [36mverbose[39m | [36mWorkflow execution finished with error[39m "{\n error: {\n name: 'NodeApiError',\n cause: Error: LoggerProxy not initialized\n at getInstance (/home/node/.n8n/nodes/node_modules/n8n-workflow/src/LoggerProxy.ts:13:9)\n at Object.debug (/home/node/.n8n/nodes/node_modules/n8n-workflow/src/LoggerProxy.ts:26:2)\n at Object.mastodonApiRequest (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:190:10)\n at Object.uploadAttachments (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:261:58)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)\n at Object.create (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:77:19)\n at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:19:21)\n at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon.node.ts:41:26)\n at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)\n at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:590:53,\n node: {\n parameters: [Object],\n id: 'eb6cdaad-cf1c-469d-aa9b-5e2d4baba983',\n name: 'Mastodon Bird Site',\n type: 'n8n-nodes-mastodon.mastodon',\n typeVersion: 1,\n position: [Array],\n credentials: [Object]\n },\n timestamp: 1679093913789,\n message: 'UNKNOWN ERROR - check the detailed error for more information',\n httpCode: null,\n description: 'LoggerProxy not initialized',\n stack: 'NodeApiError: UNKNOWN ERROR - check the detailed error for more information\\n' +\n ' at Object.mastodonApiRequest (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:195:9)\\n' +\n ' at Object.uploadAttachments (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:261:58)\\n' +\n ' at processTicksAndRejections (node:internal/process/task_queues:96:5)\\n' +\n ' at Object.create (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:77:19)\\n' +\n ' at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon_Methods.ts:19:21)\\n' +\n ' at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-mastodon/nodes/Mastodon/Mastodon.node.ts:41:26)\\n' +\n ' at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:658:28)\\n' +\n ' at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:590:53'\n },\n workflowId: '12',\n file: 'WorkflowExecute.js',\n function: 'processSuccessExecution'\n}"

n8n version: 0.220.0
Running the official docker version

**Comment by jakevis** [comment]
Rolling back to 0.216.2 fixed it... so something strange is going on

**Comment by jakevis** [comment]
Fixed in 0.222.3
